# Generated by Django 4.2.7 on 2025-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
    ]
